apiVersion: v1
kind: Service
metadata:
  name: coredns-svc-udp-lb
  annotations:
    metallb.universe.tf/allow-shared-ip: external-coredns
  namespace: kube-system
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  loadBalancerIP: 172.17.255.10
  ports:
    - name: dns-udp-lb
      protocol: UDP
      port: 53
      targetPort: 53
