---
apiVersion: "extensions/v1beta1"
kind: "Ingress"
metadata:
  name: "frontend-pub"
  namespace: "hipster-shop"
spec:
  backend:
    serviceName: "frontend"
    servicePort: 80
  rules:
    - http:
        paths:
          - path: "/"
            backend:
              serviceName: "frontend"
              servicePort: 80
