apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paymentservice
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: server
        image: rt7402/hipster-paymentservice:v0.0.2
        env:
        - name: PORT
          value: "50051"
