apiVersion: v1
kind: Pod
metadata:
  name: minio-client
spec:
  containers:
    - name: minio-client
      image: rt7402/toolbox:latest
      env:
      - name: MINIO_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: minio-secrets
            key: minio-access-key
      - name: MINIO_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: minio-secrets
            key: minio-secret-key
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi
